# Generated by Django 6.0 on 2026-09-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arch_media", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminPin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(default="default", max_length=50, unique=True),
                ),
                ("pin_hash", models.CharField(max_length=256)),
                ("version", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
